NET-342: Interactive config init
streamr-dev/network pull request #114
Opened 2021-06-28 09:37 UTC by bearni95

When saying something like:

streamr-broker init

It would start in interactive mode, asking the following:

Do you want to import an Ethereum private key or generate a new one?

[G]enerate or [I]mport

Which of the [http, mqtt, websocket] plugins do you want to enable?

Then it saves a config file into the current directory

Set Ethereum key and address to whatever the user selected

Enable the plugins that the user selected with default config

Additionally, generate 1 random API key into the config file

Print to console what was done:

Saved config file to config.json 

You can start the broker now with streamr-broker config.json

2021-07-07 14:12 UTC, harbu requested changes
Good stuff! See my comments

2021-07-07 14:12 UTC, harbu commented on packages/broker/bin/config-wizard.js
> +        console.log('action reached')
Unneeded log?

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +import {Config} from './config'
```suggestion
import { Config } from './config'
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +const TODO_VALUES = {
Something here that should be done still with `TODO_VALUES`?

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +        }
No need to run parseInt if it is empty
```suggestion
        const value = valueString === '' ? defaultValue : parseInt(valueString)
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +        if (!Number.isNaN(value) && Number.isInteger(value) && value > 1023 && value < 49151){
1) Would be best if on giving an invalid value we would print an error and prompt user to give a number again.
2) Consider renaming to `promptPortNumberWithDefault` so the range requirement `(1023, 49151)` is more clear.
3) If a user gives a number but it is outside the range, we should print a different error indicating this for clarity.

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +            if (plugins[i] === 'Websocket'){
You might want to configure your IDE to add whitespace after if/else if/else-statements for consistent styling with rest of code base.
```suggestion
            if (plugins[i] === 'Websocket') {
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +    async storeConfig(destinationFolder = '../configs/'){
Let's move the default value up to the exported function for clarity.
```suggestion
    async storeConfig(destinationFolder: string){
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +    async start(destinationFolder?: string){
```suggestion
    async start(destinationFolder: string){
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/src/ConfigWizard.ts
> +export async function startBrokerConfigWizard (destinationFolder?: string): Promise<string> {
```suggestion
export async function startBrokerConfigWizard (destinationFolder = '../configs/'): Promise<string> {
```

2021-07-07 14:12 UTC, harbu commented on packages/broker/test/unit/ConfigWizard.test.ts
> +import {unlinkSync, existsSync} from 'fs'
```suggestion
import { unlinkSync, existsSync } from 'fs'
```

2021-07-08 10:28 UTC, bearni95 commented on packages/broker/src/ConfigWizard.ts
> +const TODO_VALUES = {
@harbu the TODO_VALUES are used to prefill fields like the ethereum address as well as containing those values that seem to have no standardized definition.

Here's the config object with the current TODO_VALUES being used, may be worth discussing in today's call what to do with some of them:

```
const DefaultConfig: Config = {
    ethereumPrivateKey: TODO_VALUES.string,//'{ETHEREUM_PRIVATE_KEY}',
    network: {
        name: TODO_VALUES.string,
        hostname: '127.0.0.1', // TODO
        port: TODO_VALUES.number,
        advertisedWsUrl: null,
        trackers: [ // TODO
            "ws://127.0.0.1:30301",
            "ws://127.0.0.1:30302",
            "ws://127.0.0.1:30303"
        ],
        location: {
            latitude: 60.19,
            longitude: 24.95,
            country: "Finland",
            city: "Helsinki"
        } // TODO
    },
    reporting: {
        intervalInSeconds: 0,
        streamr: null,
        perNodeMetrics: null
    },
    streamrUrl: 'http://127.0.0.1', // TODO
    streamrAddress: '0xFCAd0B19bB29D4674531d6f115237E16AfCE377c', // TODO
    storageNodeConfig: {
        registry: {
            contractAddress: '0xbAA81A0179015bE47Ad439566374F2Bae098686F', // TODO
            jsonRpcProvider: 'http://10.200.10.1:8546' // TODO
        }
    },
    httpServer: {
        privateKeyFileName: null,
        certFileName: null,
        port: TODO_VALUES.number//'{HTTP_SERVER_PORT}',
    },
    apiAuthentication: null,
    plugins: {}
}
``

2021-07-09 12:58 UTC, harbu approved these changes
lgtm

2021-07-19 10:10 UTC, merged