feat(client): Raw subscription
streamr-dev/network pull request #1163
Opened 2023-04-04 14:28 UTC by teogeb

## Summary

Please provide a summary of the changes and a motivation if applicable.

## Changes

Provide a bullet list of individual changes. Leave this section out if change
set is small and obvious from summary.

## Limitations and future improvements

Provide a bullet list or description of known omissions or limitations of the
solution and/or any ideas for future improvement. Leave section ouf if
not applicable.

## Checklist before requesting a review

- [ ] Is this a breaking change? If it is, be clear in summary.
- [ ] Read through code myself one more time.
- [ ] Make sure any and all `TODO` comments left behind are meant to be left in.
- [ ] Has reasonable passing test coverage?
- [ ] Updated changelog if applicable.
- [ ] Updated documentation if applicable.

2023-04-06 07:46 UTC, harbu requested changes

2023-04-06 07:46 UTC, harbu commented on packages/client/test/integration/Subscriber.test.ts
> +    describe('normal subscription', () => {
```suggestion
    describe('raw subscription', () => {
```

2023-04-06 10:28 UTC, teogeb commented
Need to add some documentation about raw subscriptions to https://github.com/streamr-dev/documentation

2023-04-06 12:23 UTC, harbu commented
> Need to add some documentation about raw subscriptions to https://github.com/streamr-dev/documentation

Need or nice to have?

2023-04-11 13:14 UTC, harbu commented on packages/client/src/StreamrClient.ts
> +     */
Does this get included in the generated tsdoc or not? Fix type if needed.

2023-04-11 13:40 UTC, harbu approved these changes

2023-04-11 13:41 UTC, merged