NET-289: Update to node16
streamr-dev/network pull request #134
Opened 2021-07-28 08:25 UTC by juslesan

2021-07-28 10:03 UTC, timoxley requested changes
LGTM, though the lint/build/browser tests probably should stay without the matrix, not sure it adds any value to run them on multiple node versions.

2021-08-05 08:50 UTC, harbu approved these changes

2021-08-05 08:50 UTC, harbu commented on .github/workflows/protocol.yml
> +        node-version: [12.x, 14.x, 16.x]
Do we need to keep 12 here?

2021-08-05 09:17 UTC, juslesan commented on .github/workflows/protocol.yml
> +        node-version: [12.x, 14.x, 16.x]
Don't think so I'll remove it

2021-08-06 06:34 UTC, merged