NET-444: Config wizard; user-provided ports written as strings instead of numbers
streamr-dev/network pull request #164
Opened 2021-08-25 15:21 UTC by bearni95

The wizard's lack of type structure on the temporary configs allowed for the ports on the plugins to be provided as either strings or numbers. 

This PR assumes all given inputs will be strings for the ports and modifies the tests accordingly

2021-08-26 11:51 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +        default: defaultPluginPort.toString()
If we wan't the end result to be a `Number`, is this reverse conversion needed? I mean, if we receive a String, we should convert it to a `Number`. But this seems to do the reverse for the default. (Also at line `183`)

2021-08-26 11:56 UTC, teogeb requested changes
If we'd use the `number` input type instead of `input`, we could remove most of this conversion logic?

2021-08-26 12:22 UTC, bearni95 commented on packages/broker/src/ConfigWizard.ts
> +        default: defaultPluginPort.toString()
You're totally right, didn't even consider that `input` could be read as a number! 

Made the corresponding changes, no more casting up and down `numbers` and `strings`

2021-08-26 16:49 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +        validate: (input: number, answers: inquirer.Answers): string | boolean => {
If the input type is number, the `parseInt` is needed. But actually the type definition is wrong, I guess? Maybe worth using inquire's `filter` hook to do the conversion from string to number?

2021-08-27 09:21 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +            return parseInt(input || answers[`${pluginName}Port`])
The `answers[`${pluginName}Port`]` is always `undefined`. 

Also if an invalid number is given, the prompt will look like this:
`Select a port for the websocket Plugin [Enter for default: 7170] (7170) NaN` 
-> it is maybe impossible to input a corrected value as backspace doesn't erase the `NaN`part`

At lines 190 and 194 we don't need `parseInt` as the value is already a `number`. Maybe it would make sense the define a custom interface for `answers` to document the answer types and get warnings if there are any type annotation mismatches?

2021-08-27 09:57 UTC, bearni95 commented on packages/broker/src/ConfigWizard.ts
> +            return parseInt(input || answers[`${pluginName}Port`])
The `filter` method is the one interfering with the correction of values, pushing a fix without `filter` nor the crazy amount of casting we used to have

2021-08-27 11:14 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +            return parseInt(input || answers[`${pluginName}Port`])
Did this solve the `Select a port for the websocket Plugin [Enter for default: 7170] (7170) NaN`, or that `answers[${pluginName}Port]` is always undefined. Also isn't the `input` type of `filter` known?

2021-08-27 11:28 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +                        port: parseInt(answers[`${pluginName}Port`])
If the same modification is needed for two places, it is maybe ideal to extract the value to a separate variable so that the logic is in one place

2021-08-27 13:06 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +            const filePath = input
Could remove the redundant variable?

2021-08-27 13:08 UTC, teogeb commented on packages/broker/src/ConfigWizard.ts
> +            const portNumber = (typeof input === 'string') ? Number(input) : input
This change solved a bug, which happened if input has decimal fractions, e.g. `1234.56`. Worth mentioning in the PR description and maybe also to add a test so that we are protected from that in the future.

2021-08-27 13:14 UTC, teogeb commented on packages/broker/test/unit/ConfigWizard.test.ts
> +            const port = 3737
Currently `getConfigFromAnswers` expects that the port can be a `number` or a `string`. It could test the both situations.

2021-08-27 13:16 UTC, teogeb commented
If user gave input `7170` to the `websocket` port, it shouldn't be stored to the config file as it is the default port. Currently it stores it:
```
"websocket": {
  "port": 7170
 }
```

If user just accepts the default, it works ok and doesn't store the value.

2021-08-27 13:43 UTC, bearni95 commented
> If user gave input `7170` to the `websocket` port, it shouldn't be stored to the config file as it is the default port. Currently it stores it:
> 
> ```
> "websocket": {
>   "port": 7170
>  }
> ```
> 
> If user just accepts the default, it works ok and doesn't store the value.

Should be accounted for in the last commit

2021-08-27 13:48 UTC, teogeb commented on packages/broker/test/unit/ConfigWizard.test.ts
> +            expect(validate(port)).toBe(`Non-numeric value provided`)
Bit misleading as 55.55 is numeric value, it is just not an integer

2021-08-27 13:53 UTC, teogeb commented on packages/broker/test/unit/ConfigWizard.test.ts
> +            expect(validate(7070)).toBe(true)
The validate method still supports the string input, could keep the original test and add this string test

2021-08-30 11:53 UTC, teogeb approved these changes

2021-08-30 13:22 UTC, merged