NET-466: drop connection on tracker and kill nodes with duplicate ids
streamr-dev/network pull request #179
Opened 2021-09-02 10:27 UTC by juslesan

- To avoid confusion when sessionIds are not used, users should not be able to spin up multiple nodes with the same Ethereum private key
- Tracker now rejects connections with the same nodeId (ethereum address)
- If a node sees DUPLICATE_CONNECTION it will throw
  - UX: users won't be able to run multiple nodes with the same ethereum private key without session Ids
  - Network splits: killing duplicate nodes reduces the likelyhood of ghost networks and network splits

2021-09-02 12:28 UTC, harbu requested changes

2021-09-02 12:28 UTC, harbu commented on packages/network/test/integration/browser-ws-endpoint.test.ts
> +            await server.stop()
Probably broke indentation here, but to ensure cleanup happens: try-finally.
```suggestion
            try {
              await client1.connect(server.getUrl(), PeerInfo.newTracker('server'))
              try {
                  await client2.connect(server.getUrl(), PeerInfo.newTracker('server'))
              } catch (err) {
                  expect(err).toContain('private key')
              }
          } finally {
              await client1.stop()
              await client2.stop()
              await server.stop()
          }
```

2021-09-02 12:28 UTC, harbu commented on packages/network/test/integration/ws-endpoint.test.ts
> +            await server.stop()
try-finally cleanup here a well

2021-09-02 12:28 UTC, harbu commented on packages/network/test/integration/browser-ws-endpoint.test.ts
> +                expect(err).toContain('private key')
Maybe more fitting given the context of the test
```suggestion
                expect(err).toContain('Duplicate nodeId detected')
```

2021-09-02 12:28 UTC, harbu commented on packages/network/test/integration/ws-endpoint.test.ts
> +                expect(err).toContain('private key')
```suggestion
                expect(err).toContain('Duplicate nodeId detected')
```

2021-09-02 12:30 UTC, harbu requested changes

2021-09-02 12:30 UTC, harbu commented on packages/network/test/integration/browser-ws-endpoint.test.ts
> +            } catch (err) {
```suggestion
                await client2.connect(server.getUrl(), PeerInfo.newTracker('server'))
                fail('did not throw')
            } catch (err) {
```

2021-09-02 12:30 UTC, harbu commented on packages/network/test/integration/ws-endpoint.test.ts
> +                await client2.connect(server.getUrl(), PeerInfo.newTracker('server'))
```suggestion
                await client2.connect(server.getUrl(), PeerInfo.newTracker('server'))
                fail('did not throw')
```

2021-09-06 11:00 UTC, timoxley commented
I think this will cause problems with the brubeck client model. If every client spins up its own node, with this change, you won't be able to use  multiple clients with the same auth credentials, right?

2021-09-13 13:53 UTC, harbu approved these changes

2021-09-13 15:18 UTC, merged