feat(network): Close temporary stream connections
streamr-dev/network pull request #2306
Opened 2024-01-16 18:49 UTC by juslesan

## Summary

The TemporaryConnections were not properly closed directly after use. Instead the implementation waited for the connections to be eventually closed by the connection manager garbage collector.

The temorary connections are now closed after use with a new rpc call.

2024-01-18 15:01 UTC, harbu requested changes

2024-01-18 15:01 UTC, harbu commented on packages/trackerless-network/src/logic/RandomGraphNode.ts
> +        this.config.propagation.feedUnseenMessage(msg, this.getPropagationTargets(msg), null)
Is this change intended to be included?

2024-01-18 15:01 UTC, harbu commented on packages/trackerless-network/test/unit/TemporaryConnectionRpcLocal.test.ts
> +        await rpcLocal.openConnection(peerDescriptor, { incomingSourceDescriptor: caller } as any)
Should the 1st argument be instance of `TemporaryConnectionRequest` (de facto: unused)?

2024-01-18 15:05 UTC, teogeb reviewed
First round of comments

2024-01-18 15:05 UTC, teogeb commented on packages/trackerless-network/src/logic/RandomGraphNode.ts
> +        this.config.propagation.feedUnseenMessage(msg, this.getPropagationTargets(msg), null)
Is this change part of a separate functionality change? Or how this relates to the closing temporary connections feature?

2024-01-18 15:05 UTC, teogeb commented on packages/trackerless-network/test/unit/TemporaryConnectionRpcLocal.test.ts
> +
```suggestion
```

2024-01-18 15:05 UTC, teogeb commented on packages/trackerless-network/test/unit/TemporaryConnectionRpcLocal.test.ts
> +    it('Open Connection', async () => {
Maybe redundant test case

2024-01-18 20:10 UTC, harbu approved these changes
LGTM; I think @teogeb might've still had some points, let's wait for him to get back to this?

2024-01-22 11:53 UTC, teogeb approved these changes

2024-01-22 12:26 UTC, merged