CDN location library without data generation
streamr-dev/network pull request #2385
Opened 2024-02-20 11:37 UTC by ptesavol

* Add library for getting the current region number by asking CDN providers
* ToDo: add documentation and scripts with which the mapping between the airport code returned by CDN provider and the region number has been calculated

2024-02-20 13:05 UTC, juslesan requested changes

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +    async (timeout = 5000) => {
Could make the timeouts for different CDN queries a required parameter

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        const response = await withTimeout(fetch('https://aws.amazon.com', {
Could make a helper function to fetch the headers withTimeout something like:
```
const fetchHeaders = async (url: string, timeout: number) => {
     const { headers } = await withTimeout(fetch(url, {
          method: 'HEAD'
     }), timeout)
}
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        const airportCode = pop?.substring(0, 3)
```suggestion
        const airportCode = pop!.substring(0, 3)
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        const airportCode = pop?.substring(pop.length - 3)
```suggestion
        const airportCode = pop!.substring(pop.length - 3)
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        const airportCode = pop?.substring(pop.length - 3)
```suggestion
        const airportCode = pop!.substring(pop.length - 3)
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +    return undefined
This function could throw instead of returning undefined to make the sad path more explicit

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/test/integration/getLocalRegion.test.ts
> +    it('returns a random region if fetch is mocked to reject', async () => {
```suggestion
    it('returns a random region if requests fail', async () => {
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/test/integration/getLocalRegion.test.ts
> +    it('returns a random region if fetch is mocked to timeout', async () => {
```suggestion
    it('returns a random region if requests timeout', async () => {
```

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/tsconfig.jest.json
> +    "references": [
remove references to autocertifier-client and proto-rpc

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/tsconfig.node.json
> +    "references": [
remove references to proto-rpc and dht

2024-02-20 13:05 UTC, juslesan commented on packages/cdn-location/tsconfig.node.json
> +        "bin/**/*",
remove bin

2024-02-20 16:46 UTC, ptesavol commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +    async (timeout = 5000) => {
done

2024-02-20 16:49 UTC, ptesavol commented on packages/cdn-location/tsconfig.node.json
> +    "references": [
done

2024-02-21 08:38 UTC, juslesan requested changes

2024-02-21 08:38 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +    async (timeout = 5000) => {
```suggestion
    async (timeout: number) => {
```

2024-02-21 08:38 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +    async (timeout = 5000) => {
```suggestion
    async (timeout: number) => {
```

2024-02-21 08:38 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        if (!airportCode) {
Is this check needed? The previous check
```
if (!header || header.length < 3) {
     throw new Error('Could not get airport code from Amazon')
}
```
should ensure that the airportCode cannot be an empty string.

2024-02-21 08:38 UTC, juslesan commented on packages/cdn-location/src/fetchAirportCodeFromCdn.ts
> +        if (!airportCode) {
Same comment for `fetchAirportCodeFromFastly` and `fetchAirportCodeFromCloudflare`

2024-02-21 09:28 UTC, juslesan approved these changes

2024-02-21 11:10 UTC, merged