NET-557: validate status messages before processing
streamr-dev/network pull request #255
Opened 2021-10-18 12:06 UTC by juslesan

- Validate status messages before processing to avoid tracker crashes on conflicting versions.
- New custom WS disconnection reason/code: INVALID_PROTOCOL_MESSAGE
- In the future, there could be a range of backwards compatible protocol versions that the trackers could process.

2021-10-18 13:14 UTC, harbu requested changes

2021-10-18 13:14 UTC, harbu commented on packages/network/src/connection/ws/NodeClientWsEndpoint.ts
> +            } if (code === DisconnectionCode.VERSION_CONFICT) {
```suggestion
            } else if (code === DisconnectionCode.VERSION_CONFICT) {
```
(or newline)

2021-10-18 13:14 UTC, harbu commented on packages/network/src/connection/ws/AbstractWsEndpoint.ts
> +    VERSION_CONFICT = 4003
```suggestion
    VERSION_CONFLICT = 4003
```

2021-10-18 13:14 UTC, harbu commented on packages/network/src/logic/tracker/Tracker.ts
> +            this.trackerServer.disconnectFromPeer(source, DisconnectionCode.VERSION_CONFICT, DisconnectionReason.VERSION_CONFICT)
I don't think we can always attribute this error to be a version conflict. It could be totally something unrelated causing the error as well, e.g., a code change that causes something to break here consistently.

I think we should detect a version conflict _before the error_ occurs. Did we still exchange version information when connecting over WebSocket? Maybe this disconnection should be done at that point?

Secondly, I think we should avoid the `try-catch`-everything here. I would rather validate that variable `status` contains expected data in correct format. If not, disconnect the WebSocket maybe with reason `INVALID_STATUS_MESSAGE` or similar. 

After making sure that `status` is correct, anything that could fail afterwards would be due to a bug in our code. I don't think we should have to be defensive about our own code so I would remove the `catch`. That would make the software crash in case of an error, but I think that would be justified due to it really being a problem with our internal logic at that point.

2021-10-18 13:14 UTC, harbu commented on packages/network/test/integration/tracker-node-status.test.ts
> +    })
I would write this using `NodeToTracker` directly to avoid having to access private methods and since we don't need features of `Node`.

You can check https://github.com/streamr-dev/network-monorepo/blob/main/packages/network/test/integration/counter-filtering-in-tracker.test.ts#L35-L41 for example

2021-10-18 13:15 UTC, harbu commented on packages/network/src/logic/tracker/Tracker.ts
> +            this.trackerServer.disconnectFromPeer(source, DisconnectionCode.VERSION_CONFICT, DisconnectionReason.VERSION_CONFICT)
If I wanted to implement this quickly, I would actually just skip implementing the version check thing I described above and just validate the contents of `status` variable...

2021-10-19 10:23 UTC, harbu approved these changes
Nice, `ajv` works well here.

2021-10-19 10:23 UTC, harbu commented on packages/network/test/integration/tracker-node-disconnects-on-invalid-status.test.ts
> +            id: 'tracker'
```suggestion
            id: TRACKER_ID
```

2021-10-19 10:23 UTC, harbu commented on packages/network/test/integration/tracker-node-disconnects-on-invalid-status.test.ts
> +        await nodeToTracker.stop()
- `allSettled` to ensure that both `stop` methods get invoked (even if `tracker.stop()` rejected)
-  `?.` in case `beforeEach` threw exception in the middle (i.e. `tracker` or `nodeToTracker` was never initialized)
```suggestion
        Promise.allSettled([
            await tracker?.stop()
            await nodeToTracker?.stop()
        ])
```

2021-10-20 11:06 UTC, teogeb requested changes

2021-10-20 11:06 UTC, teogeb commented on packages/network/src/logic/tracker/Tracker.ts
> +    private readonly statusSchemaValidator: any
Would it make sense to validate the format in protocol package? There are a lot of validations already there for other message types. (Maybe we could also specify the format here: https://github.com/streamr-dev/streamr-specs/blob/master/PROTOCOL.md#statusmessage)

2021-10-20 11:06 UTC, teogeb commented on packages/network/src/connection/ws/AbstractWsEndpoint.ts
> +    INVALID_STATUS = 4003
Maybe this could be more generic, e.g. `MALFORMED_PROTOCOL_MESSAGE`?

2021-10-20 11:26 UTC, teogeb commented on packages/network/src/logic/tracker/Tracker.ts
> +    private readonly statusSchemaValidator: any
Created ticket: https://linear.app/streamr/issue/NET-568/network-move-protocol-level-logic-to-protocol-package

2021-10-20 11:27 UTC, teogeb approved these changes

2021-10-20 11:28 UTC, teogeb commented
Note that the format of the status message has changed in https://github.com/streamr-dev/network-monorepo/commit/6a453cceb1f063a3ae3d144599818f729f354bba

2022-01-27 15:01 UTC, harbu approved these changes
LGTM! :+1:  Feel free to merge to main when good for you. I'll look at the typescript in a separate PR if I have a chance.

2022-01-28 08:09 UTC, merged