Simulator
streamr-dev/network pull request #288
Opened 2021-11-26 11:45 UTC by ptesavol

This is the first version of streamr-simulator that replaces the connection layer with a simulated one with the help of Jest moduleNameMapper, and funnels all network traffic through the Simulator singleton. You can now run the network tests  in simulator using the command "npm run test-simulator" (only a few tests, such as browser tests have been excluded). 

The current version of the simulator establishes connections and passes messages without any delay (in the same tick). This extreme (and unrealistic) setting was used deliberately in order to locate and remove the risky "first do something and only then start waiting for the results" pattern from the tests. The Simulator class itself can easily be replaced using the moduleNameMapper with other implementations tailored for other use cases.  

Next versions of the Simulator will add an API to the Simulator class with features such as fetching the current topology, and adding hooks to the send and connect functions.

2021-11-26 19:05 UTC, timoxley commented on packages/network/src/connection/WebRtcConnection.ts
>                  this.close(new Error('pong not received'))
Should this `clearTimeout(this.pingTimeoutRef)` perhaps?

2021-11-26 19:05 UTC, timoxley commented on packages/network/src/connection/WebRtcEndpoint.ts
> +            return Promise.resolve(targetPeerId)
Perhaps eslint/typescript is complaining but you shouldn't need to wrap returns in `Promise.resolve`. 
`return targetPeerId` will do the same thing as `return Promise.resolve(targetPeerId)` inside an `async` function.

2021-11-26 19:05 UTC, timoxley commented on packages/network/src/connection/WebRtcEndpoint.ts
> +            return Promise.reject(new WebRtcError(`disconnected ${connection.getPeerId()}`))
Same here, just `throw`, it'll be wrapped in a rejection.

2021-11-29 14:26 UTC, timoxley commented on package.json
> +        "ci": "^2.1.1",
?

2021-11-30 16:36 UTC, juslesan requested changes
Good stuff in general!

There's a lot of comment blocks consisting of unused code that should be cleaned up before merging.

2021-11-30 16:36 UTC, juslesan commented on packages/network/package.json
> +    "leaked-handles": "^5.2.0",
clean leaked-handles debugging

2021-11-30 16:36 UTC, juslesan commented on packages/network/test/integration/webrtc-error-scenarios-during-signalling.test.ts
> +require('leaked-handles').set({
clean leaked-handles debugging

2021-11-30 16:36 UTC, juslesan commented on packages/network/test/integration/webrtc-error-scenarios-during-signalling.test.ts
> +/*
clean leaked-handles debugging

2021-11-30 16:36 UTC, juslesan commented on packages/network/test/simulator/ServerWsEndpoint_simulator.test.ts
> +    /*
Clean up commented blocks in this test file

2021-11-30 16:36 UTC, juslesan commented on packages/network/src/simulator/ServerWsEndpoint_simulator.ts
> +        return new Promise((resolve, reject) => {
clean up commented blocks of code

2021-11-30 16:36 UTC, juslesan commented on packages/network/src/simulator/ServerWsEndpoint_simulator.ts
> +    /****************** Called by Simulator ends *******/
clean up commented blocks of code

2021-12-22 09:15 UTC, merged