refactor(sdk): `StreamRegistry#populateMetadataCache()`
streamr-dev/network pull request #2885
Opened 2024-11-18 10:34 UTC by teogeb

- populateMetadataCache()
-  invalidateCache() helper function
- rename fields

2024-11-18 15:23 UTC, harbu requested changes

2024-11-18 15:23 UTC, harbu commented on packages/sdk/src/contracts/StreamRegistry.ts
> +const invalidateCache = (cache: CachingMap<string, any, any>, streamId: StreamID) => {
(nitpick) Missing return type

2024-11-18 15:23 UTC, harbu commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        return this.metadataCache.get(streamId)
The way this used to work is that when setting `useCache = false` it would just do a direct call and not use cache. Now it seems to be clearing cache. Is there a problematic scenario where if the underlying call rejects (e.g. JSON RPC is down) we clear a cache but can't provide a replace value?

Comment applies to later usages in this PR as well.

2024-11-18 15:23 UTC, harbu commented on packages/sdk/src/utils/CachingMap.ts
> +    private readonly opts: Options<P, K>
(nitpick) A `Readonly<>` here could provide more clarity to the reader that the options are not meant to change during the life of an instance of `CachingMap`.
```suggestion
    private readonly opts: Readonly<Options<P, K>>
```

2024-11-18 15:23 UTC, harbu commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        if (allowCached) {
```suggestion
        if (!allowCached) {
```

2024-11-18 15:23 UTC, harbu commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        if (allowCached) {
```suggestion
        if (!allowCached) {
```

2024-11-18 15:41 UTC, teogeb commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        return this.metadataCache.get(streamId)
Yes, that was described in the "small functionality changes" section. Calling the function with `allowCached = false` indicates that the caller needs the value to be up-to-date.  Before this change one component could have seen that stream metadata is `foo`, and another that it is `bar`. The current application wide consistency is most likely better.

I.e. it follows the principle that it is better to fail a task than to allow data corruption to happen.

2024-11-18 15:55 UTC, teogeb commented on packages/sdk/src/utils/CachingMap.ts
> +    private readonly opts: Options<P, K>
We haven't used this kind of deep annotation in the `sdk` code base before.

Many of our objects are immutable, but adding many `Readonly<>` annotations to all of those would just decrease readability. Using `readonly` in the field type is not the same, but it communicates the intention quite well.

(Also the name and the type of the field should communicate clearly that we are using the Configuration Option Pattern which implies immutability by default.)

2024-11-19 09:23 UTC, harbu commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        return this.metadataCache.get(streamId)
Yes but there can be multiple callers to the same instance of this class. Some of them might be fine with cached values and others are not. Now it could happen that one of those that is fined with cached values no longer receives the cached value because someone called this function requiring a non-cached value but the e.g. fetching fails?

2024-11-19 21:54 UTC, teogeb commented on packages/sdk/src/contracts/StreamRegistry.ts
> +        return this.metadataCache.get(streamId)
Created a separate PR for this issue: https://github.com/streamr-dev/network/pull/2889

2024-11-20 08:54 UTC, harbu approved these changes
LGTM

2024-11-20 12:46 UTC, harbu approved these changes

2024-11-20 13:14 UTC, merged